version: 2.1

orbs:
  build-tools: onemedical/build-tools@1.5.0

commands:

  create_image_tag:
    description: Create image tag based on the current branch
    steps:
      - run:
          name: Create IMAGE_TAG env var based on the current branch
          command: |
            echo 'export VERSION_TAG=branch-$(echo $CIRCLE_BRANCH | tr / -)' >> $BASH_ENV
            echo 'export RELEASE_TAG=$([[ "$CIRCLE_BRANCH" == "master" ]] && echo "latest,")' >> $BASH_ENV
            echo 'export CIRCLE_TAG=${CIRCLE_TAG:-}' >> $BASH_ENV

jobs:
  release:
    executor:
      name: build-tools/default
      resource_class: onemedical/eks-buildkit-small
    steps:
      - checkout
      - create_image_tag
      - build-tools/setup_buildkit
      - build-tools/build_and_push_image:
          repo: onemedical/aws-es-proxy
          account_id: "193567999519"
          # comma added by RELEASE_TAG if set. Kludge to get this to work is simpler than most alternatives.
          tag: '${VERSION_TAG},${VERSION_TAG}-${CIRCLE_SHA1},${RELEASE_TAG}${CIRCLE_TAG}'

workflows:
  everything:
    jobs:
      - release:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
  weekly:
    triggers:
      - schedule:
          cron: '0 12 * * 0' # In UTC; PST is 5am on Sunday
          filters:
            branches:
              only:
                - master
    jobs:
      - release
