version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

commands:

  create_image_tag:
    description: Create image tag based on the current branch
    steps:
      - run:
          name: Create IMAGE_TAG env var based on the current branch
          command: |
            echo 'export VERSION_TAG=branch-$(echo $CIRCLE_BRANCH | tr / -)' >> $BASH_ENV
            echo 'export RELEASE_TAG=$([[ "$CIRCLE_BRANCH" == "master" ]] && echo "latest,")' >> $BASH_ENV

jobs:
  release:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - create_image_tag
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          repo: onemedical/aws-es-proxy
          # comma added by RELEASE_TAG if set. Kludge to get this to work is simpler than most alternatives.
          tag: '${VERSION_TAG},${VERSION_TAG}-${CIRCLE_SHA1},${RELEASE_TAG}${CIRCLE_TAG}'

workflows:
  version: 2
  everything:
    jobs:
      - release:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
